### ISSUE TITLE
Loading button is not disabling after 3 sec.

### ISSUE THREAD

**Issue by RS-labhub** [RS-labhub/I-Love-You#1]
Someone, please fix this issue

Here's you can find it: https://github.com/RS-labhub/I-Love-You/tree/main/Pages/Page%203

https://github.com/RS-labhub/I-Love-You/assets/117426013/98ce4bf3-c0c7-48e6-9aa6-0999d4687fac

<p align="center">It should be like this<p>

**Comment by DanejSakshi13** [comment]
Hi there! I've reviewed the issue regarding the loading button. I'm confident that I can implement the required changes to address this issue effectively. Could you please assign this task to me?
Thank you!

**Comment by RS-labhub** [comment]
Okay, @DanejSakshi13 ... Thank you...

**Comment by DanejSakshi13** [comment]
Could you please confirm if these contributions align with the project's direction?
